<project>
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.beacon</groupId>
    <artifactId>beacon-parent</artifactId>
    <version>0.0.1</version>

    <packaging>pom</packaging>

    <modules>
        <module>beacon</module>
        <module>examples/openai-sdk-example</module>
        <module>examples/claude-sdk-example</module>
        <module>examples/gemini-sdk-example</module>
    </modules>

    <properties>
        <java.version>21</java.version>
    </properties>
</project>