<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.beacon</groupId>
    <artifactId>beacon</artifactId>
    <version>0.0.1</version>
    <name>Beacon</name>

    <description>A lightweight Java mock server for testing LLM applications.</description>

    <url>https://github.com/kbpramod/beacon</url>

    <licenses>
        <license>
            <name>MIT License</name>
            <url>https://opensource.org/licenses/MIT</url>
        </license>
    </licenses>
    <scm>
        <url>https://github.com/kbpramod/beacon</url>
        <connection>scm:git:https://github.com/kbpramod/beacon.git</connection>
        <developerConnection>scm:git:git@github.com:kbpramod/beacon.git</developerConnection>
    </scm>
    <developers>
        <developer>
            <id>kbpramod</id>
            <name>K B Pramod</name>
        </developer>
    </developers>

    <properties>
        <java.version>21</java.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.20.0</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <release>21</release>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
